### PR TITLE
Use SIA/Fornax instead of Astroquery for Galex access

### PR DESCRIPTION
**Pull request by tomdonaldson**
I've updated the prototype SIA service at MAST to support Galex.  This PR replaces 2 cells in the notebook to use pyvo and the Fornax cloud access API instead of Astroquery to find and download from S3 the same Galex products.

One optional TODO is that I can register the SIA service so that it can be discovered with pyvo instead of hardcoding the service URL.

I don't know if the notebook metadata changes matter but can probably remove them if needed.

### CODE REVIEW

**Comment by zoghbi-a** [comment]
I tested this and it works as expected. I suggest merging this after putting the kernel name and python version number back.

**Comment by jkrick** [comment]
Sorry I took a while to get to reviewing this, I've been on vacation.

If this PR is meant to be included in the HQ demo (which would be ideal), can you please remove the "TODO" comments and add them as issues as a way of tracking them.  That way we have a clean version for the demo.

the variable 'coords' from the first cell defines the center of the COSMOS field and is a skycoord.  Can you please switch to using that instead of the new variable 'pos'?

A quick cleanup thing: since you are touching the Galex data cells, can you please remove the commented out lines with "ra_center" and "dec_center" being sent to an individual value.  That would save me from making a new PR, thanks!

Otherwise, it looks good, and runs for me.

**Comment by tomdonaldson** [comment]
Thanks @zoghbi-a and @jkrick for the review.  I've made the requested changes:

- Remove inadvertent changes to kernel name and python version in the notebook metadata.
- Remove TODOs in the Galex cells.
- Reuse the `SkyCoord` for COSMOS in the new Galex query.
  - I briefly pulled the creation of that `coords` into a separate cell to make it easier to retest all my changes since the cell it was in was taking several minutes to run.  That conflicted with @bsipocz 's recent changes though, so it was easier to leave that in place.
- Remove the commented-out lines with `ra_center` and `dec_center` being sent to an individual value.

**Comment by tomdonaldson** [comment]
I created issues #127 and #128 to track the TODOs I removed.

**Comment by jkrick** [comment]
@tomdonaldson Thanks for making the updates, please merge.

**Comment by tomdonaldson** [comment]
> @tomdonaldson Thanks for making the updates, please merge.

@jkrick, I'll leave the merging to others on the project since I don't have write access.

**Comment by bsipocz** [comment]
> since I don't have write access

That should be fixed now, I added write access to the notebooks repo to the data-access-API, team, too.

**Comment by tomdonaldson** [comment]
> > since I don't have write access
> 
> That should be fixed now, I added write access to the notebooks repo to the data-access-API, team, too.

Thanks, @bsipocz!

**Pull request merged**
