### PR TITLE
Break heasarc TAP calls, each call has a maximum number of sources

### PR DESCRIPTION
**Pull request by zoghbi-a**
Calling the HEASARC TAP with large search areas appears to time-out. At the request of @jkrick, this PR caps the maximum number of sources in the upload table to 50000, which appears to be an optimal number that avoids making many calls, and runs in a reasonable time.

For the notebook to run, I had also to delete the following line `from sample_selection import make_coordsTable` from ztf_functions.py. `sample_selection` does not have that method. @troyraen?

### CODE REVIEW

**Comment by troyraen** [comment]
> For the notebook to run, I had also to delete the following line from sample_selection import make_coordsTable from ztf_functions.py. sample_selection does not have that method. @troyraen?

This is getting fixed in #176

**Review by jkrick — COMMENTED** [review]
looks good to me and runs for both a small sample and a sample which needs to be broken up.  I have not yet tried 500k sources.  Thanks for implementing the changes. My only request is to add some comment lines around what you are doing in heasarc_functions.py so it is clear for anyone reading the code.

**Comment by jkrick** [comment]
And now I can confirm that it works on the 500k sample.

**Comment by zoghbi-a** [comment]
Thanks @jkrick for testing this.
I have now rebased to include the latest changes in the main branch, and added some comments.

**Pull request merged**
