### PR TITLE
Clean up plot_functions.py

### LINKED ISSUE #199: Clean up plot_functions.py
This issue was separated from #177.

The following refer to the `create_figures` function unless otherwise indicated.

- [x] Remove `sample_table` as an argument. Iterate over `df_lc` (grouped by `objectid`) instead of `sample_table` rows.
- [x] Remove the manual counter `cc`. If this counter is really needed, get it by adding `enumerate` to the `for` loop.
- [x] The function is very long function; breaking it up into smaller ones would improve readability. Consider making separate functions each band (or group of bands) and for the formatting.
- [x] Remove function `setup_text_plots` because it is not being used anywhere.

### PR DESCRIPTION
**Pull request by troyraen**
Closes #199 
(This should be merged *after* #198)

## Changes
- separate `create_figures` into smaller functions
- remove `sample_table` arg and `cc` manual counter
- remove unused function `setup_text_plots`

## Of Note

Bands with fluxes in electrons/sec ('Kepler', 'K2', 'TESS') are now scaled based on all bands with fluxes in mJy. Previously they were being scaled based only on the bands that had actually been plotted before the electrons/sec bands; and if no bands had already been plotted, the electrons/sec band was omitted. I can provide figures for comparison if anyone wants to see them.

I have removed the line that dropped data points with "time" > 65000 MJD (= 2036-11-03). I checked the Yang sample and the first 100 objects in the SDSS sample and did not find any such data points. If there was a specific need for that line, please let me know. It seems to me that, if there are any such data points, they should be dropped from the dataframe altogether, not just for plotting.

### CODE REVIEW

**Review by jkrick — APPROVED** [review]
Thanks for tackling this plotting function.  I  like how you divided it up into separate functions, so now it is way easier to manage.

I will defer to Andreas to check the plotting.  I did run it on the SMCE, and the plots appear by quick glance to be reasonable.  

I agree that anything with an erroneous future dates should be removed at some data cleaning place in the ML notebook (I made a note for myself)

Now that the plotting function is more organized, is it possible to make the plotting colors band specific (ie., so in every plot W1 is always gray, W2 is always black, etc.)?  It would be a nice enhancement, not required at all.

**Comment by jkrick** [comment]
I like the idea of dropping NaN's from the data frame before plotting.  Can that go in the new` _clean_lightcurves` before the `zscore` gets calculated?  for issue #203

**Review by afaisst — APPROVED** [review]
I ran it through on SMCE and all looks good.

Regarding "Of Note" #2: I don't know why we imposed a cut at high MJDs. There might have been a problem in the beginning (wrong data?), but that seems to not occur anymore. I agree that if there is a case like this, we would have to remove it from the data frame all together.

**Review by bsipocz — APPROVED** [review]
The refactoring looks good to me, thank you for doing this cleanup!

**Comment by troyraen** [comment]
> Now that the plotting function is more organized, is it possible to make the plotting colors band specific (ie., so in every plot W1 is always gray, W2 is always black, etc.)? It would be a nice enhancement, not required at all.

Sure, done. Here is what the colors are now. (And if folks don't like certain assignments, they can be changed.)

lightcurve_100

**Comment by troyraen** [comment]
> I like the idea of dropping NaN's from the data frame before plotting. Can that go in the new `_clean_lightcurves` before the `zscore` gets calculated? for issue https://github.com/fornax-navo/fornax-demo-notebooks/issues/203

Done

**Pull request merged**
