### PR TITLE
Faisst update mar232023

### PR DESCRIPTION
**Pull request by afaisst**
Several Changes:
- Imported pickle in data_structure.py as it was missing
- Added binning to ZTF data in zoom-in figure
- Gaia to function. Gaia light curve can now be created in one line. I added another function to create a plot of the Gaia light curves. Can be skipped if no plot required.
- IceCube to function. IceCube neutrino matching can now be done in one line
- IceCube data is now stored externally on my personal Caltech Box (not ideal) and fully removed from GitHub. The IceCube function downloads and unzippes the IceCube data if it is not downloaded already.

### CODE REVIEW

**Comment by jkrick** [comment]
PR looks good to me.  Do you want to resolve conflicts? or do you want me to try?

**Comment by bsipocz** [comment]
I'm happy to fix the conflict, too, notebooks are notoriously ugly to conflict resolve with an editor.

**Comment by afaisst** [comment]
*   What are the lightcurve pdf files in the data directory? They seem to be generated to me, thus should not be part of the repo, but I maybe mistaken.
I left two of them in there so people can look at them without running the whole thing. For example, we can show them during the meetings.

Andreas

From: Brigitta Sipőcz ***@***.***>
Date: Wednesday, March 29, 2023 at 10:48 AM
To: fornax-navo/fornax-demo-notebooks ***@***.***>
Cc: Andreas Faisst ***@***.***>, Assign ***@***.***>
Subject: Re: [fornax-navo/fornax-demo-notebooks] Faisst update mar232023 (PR #92)

There are some high-level things here that may need addressing in addition to the rebase for the conflicts:

  *   Some of the conflicts come from the metadata differences, we may need to start to use more strict environments so to avoid those, or be more careful and do partial commits that skip those rather than full files (but it would be everything but convenient).
  *   I think it would be useful to reach a consensus on whether to include outputs and execute metadata in the notebooks or not, going back and forth in the repo history is not ideal.
  *   What are the lightcurve pdf files in the data directory? They seem to be generated to me, thus should not be part of the repo, but I maybe mistaken.

**Comment by bsipocz** [comment]
We have bigger fishes to fry than the clean metadata, but e.g. I keep seeing these back and forth (also in the "Notebook metadata changed" drop down, in the github rendering):

```
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 ```
 
 vs
 
```
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 ```

**Comment by bsipocz** [comment]
> I left two of them in there so people can look at them without running the whole thing. For example, we can show them during the meetings.

I think it would be worth to discuss the purpose of this repo. I agree that a place is nice to have for internal team discussions and showcases, but my personal preference for something we serve for the outside world is a repo with clean history without temporary files, etc. 
But I think it's possible to have both, we'll just need to separate the development process from the final product, e.g. treat this as a sandbox repo, and have another one for the deployed, "finished" product?

**Comment by afaisst** [comment]
We probably have to write an example doc or tutorial if we eventually publish it. So, we could leave one output figure in there…

**Comment by jkrick** [comment]
Thanks for the clarification and the help prioritizing.  Let's leave some of those fish in the water.  We'll try to clear output before pushing but leave the metadata and `--patch` commits for another day.  Let's talk about clean repos vs. useful while working on them repos at the meeting this afternoon.

**Comment by bsipocz** [comment]
@afaisst - you may want to add your ipac email to your github profile, so your commits are correctly identified as yours on github (e.g. the ones above are not mine, and are correctly not mine in the git log, but the interface shows them incorrectly as your email address cannot be identified)

**Pull request merged**
