### PR TITLE
Move root-level `code` and `data` directories under `forced_photometry`

### LINKED ISSUE #106: Re-evaluate directory structure for code and data files
Currently, the data and code used by the forced_photometry notebook is stored in the corresponding subdirectories of the repo's _root_ directory while the light_curves notebook stores in subdirectories of the light_curves directory. Now that we have two examples, we could re-evaluate how we're organizing those files.

### PR DESCRIPTION
**Pull request by troyraen**
Closes #106 

Moves root-level `code` & `data` directories under the `forced_photometry` directory.

### CODE REVIEW

**Comment by troyraen** [comment]
This is ready, but I'll leave it as a draft PR because we don't want to merge it yet (as discussed with the IRSA SP team earlier today). The SCME folks are actively working with this notebook so we'll pause this PR to avoid unnecessary complications.

**Comment by troyraen** [comment]
Since the multiband_photometry.ipynb notebook is actively being worked on, I'd like to just close this PR and re-do it after the other work is complete. These are easy changes to make at any time, so I see no benefit to leaving this PR open and then having to resolve the conflicts. (@jkrick)

**Comment by troyraen** [comment]
Since the multiband_photometry.ipynb notebook is actively being worked on, I'd like to just close this PR and re-do it after the other work is complete. These are easy changes to make at any time, so I see no benefit to leaving this PR open and then having to resolve the conflicts. (@jkrick)

**Comment by bsipocz** [comment]
The other option is to leave it open as a draft and place-holder, and then redo stuff and push it back to this branch. But either way is good, thanks @troyraen!

**Pull request closed without merging**
